### ISSUE TITLE
Adjust axis tags

### ISSUE THREAD

**Issue by b4rdha** [MajaLinder/SEMFIRE#48]
- Adjust color to the Spotfire gray ( see figma for colorscheme) 
- Adjust font size to use Spotfire figma prototype 

Must use API values instead of setting colors. 

Acceptance Criteria: Colours of the tags must match the colours of the Spotfire figma prototype. 

Planning poker score: 5 (0-89 Fibonacci)

**Comment by LIYUHAN22** [comment]
![Image](https://user-images.githubusercontent.com/102019782/195383808-713134d2-8bd8-4d14-8040-46a976c74963.png)

**Comment by LIYUHAN22** [comment]
![Image](https://user-images.githubusercontent.com/102019782/195414299-81c3cff8-67b5-4d8d-9060-0ee6ea26b912.png)

I'm not sure what the problem is, I think maybe is the responding problem?

![Image](https://user-images.githubusercontent.com/102019782/195414324-e78ef8ad-31b4-4491-a858-26a5b3372005.png)
